### ISSUE TITLE
SSL Certificate expired

### ISSUE THREAD

**Issue by mlazzje** [skx/dns-api.org#10]
You SSL certificate appears to be expired.
 
https://dns-api.org/ (Chrome and Firefox)

![image](https://user-images.githubusercontent.com/5486652/31653631-83c6d6ec-b323-11e7-8dc8-625c2bd79d1e.png)

**Comment by skx** [comment]
Already resolved, but thank-you for the bug report :)

**Comment by mlazzje** [comment]
Thank you for your work :)
