### ISSUE TITLE
logs directory does not exist at first startup

### ISSUE THREAD

**Issue by mgoins01** [skx/dns-api.org#14]
Thanks for the good work on dns-api.org - have been looking for open-source capability to use in recon phase of getting our arms around our external website footprint - we've recently acquired several companies, with many marketing websites, and no good single list to go from.  So, am using various kali tools to identify them, and where they're hosted, in helping to plan an upcoming pen-test.

dns-api.org looks to fit the bill - have been working on installing on my kali instance.

That said, after having installed the pre-reqs:
- Plackup via "curl -L https://cpanmin.us | perl - --sudo App::cpanminus"
- and, cpanminus via "cpanm Plack"

I ran the run command from the ./dns-api.org directory, and it failed with 'no such file' referencing the logs directory:

root@kali:/home/ec2-user/dns-api.org# ./run
Launching on 127.0.0.1:5001
open(logs/access.2018-02-11.log): No such file or directory at /usr/local/share/perl/5.26.1/Plack/Runner.pm line 268.

A workaround is to manually create the logs directory via mkdir.  May want to add creation of the logs directory to the repo for the next release.   Thanks.

**Comment by skx** [comment]
Thanks for the bug-report, I've updated `./run` to create the directory now.

**Comment by mgoins01** [comment]
wow - that was quick.

? - should i be able to redirect port 5001 via putty, and hit this w/a browser, like so?
http://localhost:5001/A/www.google.com

i've fired dns-api up on my kali box, and see it's listening on 5001, but am seeing 'waiting for localhost' on Chrome, and nothing shows up in the dns-api log.

**Comment by skx** [comment]
> wow - that was quick.

Just happened to be checking my email at the time your report came in :)

> - should i be able to redirect port 5001 via putty, and hit this w/a browser, like so?
> http://localhost:5001/A/www.google.com

Yes.  Providing you have the port-forwarded _and_ the server/service is running on the remote host then it should just work.  Nothing specific about the tool here.

> i've fired dns-api up on my kali box, and see it's listening on 5001, but am seeing 'waiting for localhost' on Chrome, and nothing shows up in the dns-api log.

You might try being explicit "`http://127.0.0.1:5001/A/example.com`" just to rule out IPv6, or DNS.  But I'd expect it to just work.  You could test via opening a terminal on your system, after the forwarding has been enabled and trying:

       telnet 127.0.0.1 5001

If you get "connection refused" then the forwarding is broken, or the service/server isn't running.  If you get a connection and can enter "`GET /a/steve.com HTTP/1.0\n\n`", etc. then all is well.

**Comment by mgoins01** [comment]
thanks - on the port forwarding, found that my host firewall was preventing it.  

Have one more - am looking to increase the rate limits - how fast have you seen this run?

Found in the ./bin/dns-api file a place that appears to allow setting rate-limits.  Have changed the limit from 200/hr to 1000/hr to up the speed, but am seeing relatively slow performance.  CPU / memory usage is low on my kali box, so am not sure where the slowdown is.

enable 'Plack::Middleware::Throttle::JSON',
      backend => 'Simple',
      limits  => '1000 req/hour',
      routes  => '/';

**Comment by skx** [comment]
> Have one more - am looking to increase the rate limits - how fast have you seen this run?

How fast I've seen it run doesn't matter - it is how fast _you_ see it run that counts.

You can test it with apache bench (`ab`), `siege`, or similar.

But it isn't my code that will be slow, the limiting factor will be the speed of the DNS servers you're using (as the code just does DNS it's the system lookups that will eat the time.  You can update /etc/resolv.conf if your current servers are very slow.)

>Found in the ./bin/dns-api file a place that appears to allow setting rate-limits. Have changed the limit from 200/hr to 1000/hr to up the speed, but am seeing relatively slow performance. CPU / memory usage is low on my kali box, so am not sure where the slowdown is.

Will be the system resolving.  You can confirm using your favourite debugging tools.   The rate limit change is good - but if you hit the rate-limit you'll find out, as you'll start getting back errors rather than JSON bodies.

(Something I added because people abuse my public installation.)

**Comment by mgoins01** [comment]
thanks for the hints.  Am running on an AWS EC2 instance - found that /etc/resolv.conf pointed back thru AWS infrastructure - changed to 8.8.8.8 (Google), and it took off.  Performance much better - thanks!
