### ISSUE TITLE
Net::DNS has returned undef to the caller

### ISSUE THREAD

**Issue by Amolmahajan7** [skx/dns-api.org#6]
Hello,

While running NS check  Value are "value" : null, and WARNING!!!  The program has attempted to call the method
***  "rdstring" for the following RR object:
***
***  dns-api.org.       258039  IN      NS      c.ns.bytemark.co.uk.
***
***  This object does not have a method "rdstring".  THIS IS A BUG
***  IN THE CALLING SOFTWARE, which has incorrectly assumed that
***  the object would be of a particular type.  The calling
***  software should check the type of each RR object before
***  calling any of its methods.
***
***  Net::DNS has returned undef to the caller.
***

 at /home/amydns/public_html/lib/DNS/API.pm line 104.

What has caused this issue
server details:
CloudLinux release 7.3

Regards,
Amol

**Comment by skx** [comment]
Could you tell me what URL you're hitting to trigger that output?

I assumed you were looking for a `NS` record, like so:

* https://dns-api.org/NS/dns-api.org
* https://dns-api.org/NS/dns-api.org.
* https://dns-api.org/ns/dns-api.org
* https://dns-api.org/ns/dns-api.org.

Each of those seems to be OK for me though, so I'm a little unsure where to handle this.

A simple patch might be the following, but I'm not sure if it's going to do horrible things!

      deagol ~/Repos/websites/dns-api.org $ git diff
      diff --git a/lib/DNS/API.pm b/lib/DNS/API.pm
      index 6825085..c040866 100755
      --- a/lib/DNS/API.pm
      +++ b/lib/DNS/API.pm
      @@ -101,7 +101,8 @@ sub lookup
                       $x{ 'type' }  = $rr->type();
                       $x{ 'ttl' }   = $rr->ttl();
                       $x{ 'name' }  = $rr->name();
      -                $x{ 'value' } = $rr->rdstring();
      +                $x{ 'value' } = "unknown";
      +                $x{ 'value'}  = $rr->rdstring() if ( UNIVERSAL::can( $rr, "rdstring" ) );
       
                       push( @result, \%x );
                   }

**Comment by Amolmahajan7** [comment]
Hello,

Thank you for replying.
The problem URL is : http://67.23.226.181:5001/NS/dns-api.org
Regards,
Amol

**Comment by skx** [comment]
OK I can confirm I see `"value":null,` in the output, which shows that it is broken.

I __think__ this means that your nameservers are not working as expected.  Can you login to that host and run:

    $ cat /etc/resolve.conf

Then run this for each IP you have listed in that file:

     dig -t ns dns-api.org $ip

I expect you'll get the IPs via:

      grep nameserver /etc/resolv.conf | awk '{print $2}'

If your nameservers are returning data that is odd/bogus/broken then I suspect that I cannot do much about it, but it'll be interesting to find out for sure.

**Comment by skx** [comment]
Also please run:

    $ perl -MNet::DNS -e 'print $Net::DNS::VERSION . "\n"'

It might be a version change from what I'm using (0.81).

**Comment by Amolmahajan7** [comment]
Hello,

Below is the output by provided commands.
---------------------
grep nameserver /etc/resolv.conf | awk '{print $2}'
66.7.206.2
66.7.207.2
root@atlas [/home/amydns/public_html]# dig -t ns dns-api.org 66.7.206.2

; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3.2 <<>> -t ns dns-api.org 66.7.206.2
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24467
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dns-api.org.                   IN      NS

;; ANSWER SECTION:
dns-api.org.            258489  IN      NS      a.ns.bytemark.co.uk.
dns-api.org.            258489  IN      NS      b.ns.bytemark.co.uk.
dns-api.org.            258489  IN      NS      c.ns.bytemark.co.uk.

;; Query time: 4 msec
;; SERVER: 66.7.206.2#53(66.7.206.2)
;; WHEN: Wed Apr 05 09:03:54 EDT 2017
;; MSG SIZE  rcvd: 105

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 34999
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;66.7.206.2.                    IN      NS

;; AUTHORITY SECTION:
.                       45084   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2017040500 1800 900 604800 86400

;; Query time: 39 msec
;; SERVER: 66.7.206.2#53(66.7.206.2)
;; WHEN: Wed Apr 05 09:03:54 EDT 2017
;; MSG SIZE  rcvd: 114

root@atlas [/home/amydns/public_html]# dig -t ns dns-api.org 66.7.207.2

; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3.2 <<>> -t ns dns-api.org 66.7.207.2
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2139
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dns-api.org.                   IN      NS

;; ANSWER SECTION:
dns-api.org.            258469  IN      NS      a.ns.bytemark.co.uk.
dns-api.org.            258469  IN      NS      b.ns.bytemark.co.uk.
dns-api.org.            258469  IN      NS      c.ns.bytemark.co.uk.

;; Query time: 3 msec
;; SERVER: 66.7.206.2#53(66.7.206.2)
;; WHEN: Wed Apr 05 09:03:59 EDT 2017
;; MSG SIZE  rcvd: 105

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 3941
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;66.7.207.2.                    IN      NS

;; AUTHORITY SECTION:
.                       45413   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2017040500 1800 900 604800 86400

;; Query time: 211 msec
;; SERVER: 66.7.206.2#53(66.7.206.2)
;; WHEN: Wed Apr 05 09:03:59 EDT 2017
;; MSG SIZE  rcvd: 114

root@atlas [/home/amydns/public_html]# perl -MNet::DNS -e 'print $Net::DNS::VERSION . "\n"'
0.70_01
---------------------

Regards,
Amol

**Comment by skx** [comment]
OK that was useful, thank-you.

* You've got a pair of nameservers.
   * Both of them return the correct results when you query them directly.
* Your `Net::DNS` module is pretty old.
   * I've run the same version and I don't see the same error.

Can you try running the program here and seeing what it shows?

* https://pastebin.com/n3xrqmWF

It's basically the same code, but I'm curious to see if it shows any error here.

**Comment by Amolmahajan7** [comment]
Output for the program is as below.

=------------------
root@atlas [/home/amydns/public_html]# perl test
Version 955

***
***  WARNING!!!  The program has attempted to call the method
***  "rdstring" for the following RR object:
***
***  dns-api.org.       259151  IN      NS      a.ns.bytemark.co.uk.
***
***  This object does not have a method "rdstring".  THIS IS A BUG
***  IN THE CALLING SOFTWARE, which has incorrectly assumed that
***  the object would be of a particular type.  The calling
***  software should check the type of each RR object before
***  calling any of its methods.
***
***  Net::DNS has returned undef to the caller.
***

 at test line 26.

***
***  WARNING!!!  The program has attempted to call the method
***  "rdstring" for the following RR object:
***
***  dns-api.org.       259151  IN      NS      b.ns.bytemark.co.uk.
***
***  This object does not have a method "rdstring".  THIS IS A BUG
***  IN THE CALLING SOFTWARE, which has incorrectly assumed that
***  the object would be of a particular type.  The calling
***  software should check the type of each RR object before
***  calling any of its methods.
***
***  Net::DNS has returned undef to the caller.
***

 at test line 26.

***
***  WARNING!!!  The program has attempted to call the method
***  "rdstring" for the following RR object:
***
***  dns-api.org.       259151  IN      NS      c.ns.bytemark.co.uk.
***
***  This object does not have a method "rdstring".  THIS IS A BUG
***  IN THE CALLING SOFTWARE, which has incorrectly assumed that
***  the object would be of a particular type.  The calling
***  software should check the type of each RR object before
***  calling any of its methods.
***
***  Net::DNS has returned undef to the caller.
***

 at test line 26.
$VAR1 = [
          {
            'value' => undef,
            'ttl' => 259151,
            'name' => 'dns-api.org',
            'type' => 'NS'
          },
          {
            'value' => undef,
            'ttl' => 259151,
            'name' => 'dns-api.org',
            'type' => 'NS'
          },
          {
            'value' => undef,
            'ttl' => 259151,
            'name' => 'dns-api.org',
            'type' => 'NS'
          }
        ];

----------------

**Comment by skx** [comment]
Definitely something wrong, but I cannot reproduce that here at all :(

**Comment by Amolmahajan7** [comment]
Hello,

Fixed it with installing http://www.cpan.org/authors/id/N/NL/NLNETLABS/Net-DNS-0.81.tar.gz
Thank you.
