### ISSUE TITLE
Change Docker Base-Image

### ISSUE THREAD

**Issue by justb81** [skx/dns-api.org#9]
Your Dockerfile defines [ytnobody/alpine-perl:latest](https://hub.docker.com/r/ytnobody/alpine-perl/) as Base-Image. This image is not maintained since 2 years. Use a basic alpine and install perl by yourself or use the tiny-tag (`ytnobody/alpine-perl:tiny`), that is maintained 10 months ago.

**Comment by skx** [comment]
Sounds about right, this Dockerfile was probably created at that time.

I'll update the base in the near future.
